"""
youtube_uploader.py — Uploads the final Short to YouTube.

Requirements:
  - client_secret.json in project root (from Google Cloud Console)
  - token.pickle in project root (generated by auth_youtube.py)
"""

import os
import pickle
from dotenv import load_dotenv
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google.auth.transport.requests import Request

load_dotenv()


def get_authenticated_service():
    """Loads saved credentials and returns an authenticated YouTube service."""
    token_path = "token.pickle"
    credentials = None

    if os.path.exists(token_path):
        with open(token_path, "rb") as token:
            credentials = pickle.load(token)

    # Refresh if expired
    if credentials and credentials.expired and credentials.refresh_token:
        credentials.refresh(Request())
        with open(token_path, "wb") as token:
            pickle.dump(credentials, token)

    if not credentials or not credentials.valid:
        raise RuntimeError(
            "YouTube credentials not found or invalid.\n"
            "Run: python auth_youtube.py\n"
            "to generate token.pickle first."
        )

    return build("youtube", "v3", credentials=credentials)


def upload_video(video_path: str, title: str = None, description: str = None) -> str:
    """
    Uploads a video file as a YouTube Short.

    Args:
        video_path: Absolute path to the MP4 file.
        title:      Video title (defaults to filename).
        description: Video description.

    Returns:
        The YouTube video URL string.
    """
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video file not found: {video_path}")

    youtube = get_authenticated_service()

    # Default title = filename without extension
    if not title:
        title = os.path.splitext(os.path.basename(video_path))[0]

    if not description:
        description = (
            "🤖 Auto-generated YouTube Short.\n"
            "#Shorts #Facts #DidYouKnow #Viral"
        )

    print(f"📤 Uploading '{title}' to YouTube...")

    request_body = {
        "snippet": {
            "title": title,
            "description": description,
            # The #Shorts tag is critical for the algorithm to classify it as a Short
            "tags": ["Shorts", "Facts", "DidYouKnow", "Viral", "Educational"],
            "categoryId": "22",          # "People & Blogs" — works well for Shorts
            "defaultLanguage": "en",
        },
        "status": {
            "privacyStatus": "public",   # Change to "private" for testing
            "selfDeclaredMadeForKids": False,
        },
    }

    media = MediaFileUpload(
        video_path,
        mimetype="video/mp4",
        resumable=True,             # Allows retrying large uploads
        chunksize=4 * 1024 * 1024,  # 4 MB chunks
    )

    upload_request = youtube.videos().insert(
        part="snippet,status",
        body=request_body,
        media_body=media,
    )

    response = None
    while response is None:
        status, response = upload_request.next_chunk()
        if status:
            percent = int(status.progress() * 100)
            print(f"   ⬆️  Upload progress: {percent}%")

    video_id = response["id"]
    video_url = f"https://www.youtube.com/shorts/{video_id}"
    print(f"✅ Uploaded! Video URL: {video_url}")
    return video_url
